language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - pip install useragent fake_useragent
script:
  - "sudo sh Setup.sh"
  - "sudo ./SimplyEmail.py -l"
  - "sudo ./SimplyEmail.py -h"
  - "sudo ./SimplyEmail.py -n"
  - "sudo ./SimplyEmail.py -verify"
  - "sudo ./SimplyEmail.py -s"
  - "sudo ./SimplyEmail.py -s -e cybersyndicates.com"
  - nosetests --with-coverage
after_success:
  - coveralls
  
