language: python
python:
  - "2.7"
script:
  - "sudo sh Setup.sh"
  - "sudo pip install python-coveralls"
  - "sudo ./SimplyEmail.py -l"
  - "sudo ./SimplyEmail.py -h"
  - "sudo ./SimplyEmail.py -n"
  - "sudo ./SimplyEmail.py -verify"
  - "sudo ./SimplyEmail.py -s"
  - "sudo ./SimplyEmail.py -s -e cybersyndicates.com"
after_success:
  - coveralls
  
